import EntityCrudPage from '../../shared/EntityCrudPage';
import { useLoanList, useCreateLoan, useLoan, useUpdateLoan } from '../../../features/portfolio/loans/api';
import { useAssetList, useCreateAsset, useAsset, useUpdateAsset } from '../../../features/portfolio/assets/api';
import { usePaymentList, useCreatePayment, usePayment, useUpdatePayment } from '../../../features/servicing/payments/api';
import { useInspectionList, useCreateInspection, useInspection, useUpdateInspection } from '../../../features/servicing/inspections/api';
import { useDrawList, useCreateDraw, useDraw, useUpdateDraw } from '../../../features/servicing/draws/api';
import { useEscrowList, useCreateEscrow, useEscrow, useUpdateEscrow } from '../../../features/servicing/escrows/api';
import { useBorrowerFinancialList, useCreateBorrowerFinancial, useBorrowerFinancial, useUpdateBorrowerFinancial } from '../../../features/servicing/borrowerFinancials/api';
import { useManagementItemList, useCreateManagementItem, useManagementItem, useUpdateManagementItem } from '../../../features/servicing/management/api';
import { useComplianceItemList, useCreateComplianceItem, useComplianceItem, useUpdateComplianceItem } from '../../../features/governance/complianceItems/api';
import { useLegalItemList, useCreateLegalItem, useLegalItem, useUpdateLegalItem } from '../../../features/governance/legalItems/api';
import { useRegulatoryScanList, useCreateRegulatoryScan, useRegulatoryScan, useUpdateRegulatoryScan } from '../../../features/governance/regulatoryScans/api';
import { useRiskItemList, useCreateRiskItem, useRiskItem, useUpdateRiskItem } from '../../../features/governance/riskItems/api';
import { useDocumentReviewList, useCreateDocumentReview, useDocumentReview, useUpdateDocumentReview } from '../../../features/governance/documentReviews/api';
import { usePoolList, useCreatePool, usePool, useUpdatePool } from '../../../features/markets/pools/api';
import { useTokenList, useCreateToken, useToken, useUpdateToken } from '../../../features/markets/tokens/api';
import { useTradeList, useCreateTrade, useTrade, useUpdateTrade } from '../../../features/markets/trades/api';
import { useExchangeListingList, useCreateExchangeListing, useExchangeListing, useUpdateExchangeListing } from '../../../features/markets/exchangeListings/api';
import { useReportList, useCreateReport, useReport, useUpdateReport } from '../../../features/reports/reports/api';
import { useOrganizationList, useCreateOrganization, useOrganization, useUpdateOrganization } from '../../../features/organizations/organizations/api';

export const PortfolioLoansPage = () => <EntityCrudPage title="Loans" createLabel="Create Loan" hooks={{ useList: useLoanList, useCreate: useCreateLoan, useItem: useLoan, useUpdate: useUpdateLoan }} />;
export const PortfolioAssetsPage = () => <EntityCrudPage title="Assets" createLabel="Create Asset" hooks={{ useList: useAssetList, useCreate: useCreateAsset, useItem: useAsset, useUpdate: useUpdateAsset }} />;
export const ServicingPaymentsCrudPage = () => <EntityCrudPage title="Payments" createLabel="Create Payment" hooks={{ useList: usePaymentList, useCreate: useCreatePayment, useItem: usePayment, useUpdate: useUpdatePayment }} />;
export const ServicingInspectionsCrudPage = () => <EntityCrudPage title="Inspections" createLabel="Create Inspection" hooks={{ useList: useInspectionList, useCreate: useCreateInspection, useItem: useInspection, useUpdate: useUpdateInspection }} />;
export const ServicingDrawsCrudPage = () => <EntityCrudPage title="Draws" createLabel="Create Draw" hooks={{ useList: useDrawList, useCreate: useCreateDraw, useItem: useDraw, useUpdate: useUpdateDraw }} />;
export const ServicingEscrowsCrudPage = () => <EntityCrudPage title="Escrows" createLabel="Create Escrow" hooks={{ useList: useEscrowList, useCreate: useCreateEscrow, useItem: useEscrow, useUpdate: useUpdateEscrow }} />;
export const ServicingBorrowerFinancialsCrudPage = () => <EntityCrudPage title="Borrower Financials" createLabel="Create Financial" hooks={{ useList: useBorrowerFinancialList, useCreate: useCreateBorrowerFinancial, useItem: useBorrowerFinancial, useUpdate: useUpdateBorrowerFinancial }} />;
export const ServicingManagementCrudPage = () => <EntityCrudPage title="Management" createLabel="Create Item" hooks={{ useList: useManagementItemList, useCreate: useCreateManagementItem, useItem: useManagementItem, useUpdate: useUpdateManagementItem }} />;
export const GovernanceComplianceCrudPage = () => <EntityCrudPage title="Compliance Items" createLabel="Create Compliance Item" hooks={{ useList: useComplianceItemList, useCreate: useCreateComplianceItem, useItem: useComplianceItem, useUpdate: useUpdateComplianceItem }} />;
export const GovernanceLegalCrudPage = () => <EntityCrudPage title="Legal Items" createLabel="Create Legal Item" hooks={{ useList: useLegalItemList, useCreate: useCreateLegalItem, useItem: useLegalItem, useUpdate: useUpdateLegalItem }} />;
export const GovernanceRegulatoryCrudPage = () => <EntityCrudPage title="Regulatory Scans" createLabel="Create Regulatory Scan" hooks={{ useList: useRegulatoryScanList, useCreate: useCreateRegulatoryScan, useItem: useRegulatoryScan, useUpdate: useUpdateRegulatoryScan }} />;
export const GovernanceRiskCrudPage = () => <EntityCrudPage title="Risk Items" createLabel="Create Risk Item" hooks={{ useList: useRiskItemList, useCreate: useCreateRiskItem, useItem: useRiskItem, useUpdate: useUpdateRiskItem }} />;
export const GovernanceDocumentCrudPage = () => <EntityCrudPage title="Document Reviews" createLabel="Create Document Review" hooks={{ useList: useDocumentReviewList, useCreate: useCreateDocumentReview, useItem: useDocumentReview, useUpdate: useUpdateDocumentReview }} />;
export const MarketsPoolsCrudPage = () => <EntityCrudPage title="Pools" createLabel="Create Pool" hooks={{ useList: usePoolList, useCreate: useCreatePool, useItem: usePool, useUpdate: useUpdatePool }} />;
export const MarketsTokensCrudPage = () => <EntityCrudPage title="Tokens" createLabel="Create Token" hooks={{ useList: useTokenList, useCreate: useCreateToken, useItem: useToken, useUpdate: useUpdateToken }} />;
export const MarketsTradesCrudPage = () => <EntityCrudPage title="Trades" createLabel="Create Trade" hooks={{ useList: useTradeList, useCreate: useCreateTrade, useItem: useTrade, useUpdate: useUpdateTrade }} />;
export const MarketsExchangeCrudPage = () => <EntityCrudPage title="Exchange Listings" createLabel="Create Listing" hooks={{ useList: useExchangeListingList, useCreate: useCreateExchangeListing, useItem: useExchangeListing, useUpdate: useUpdateExchangeListing }} />;
export const ReportsCrudPage = () => <EntityCrudPage title="Reports" createLabel="Create Report" hooks={{ useList: useReportList, useCreate: useCreateReport, useItem: useReport, useUpdate: useUpdateReport }} />;
export const OrganizationsCrudPage = () => <EntityCrudPage title="Organizations" createLabel="Create Organization" hooks={{ useList: useOrganizationList, useCreate: useCreateOrganization, useItem: useOrganization, useUpdate: useUpdateOrganization }} />;
