// ─── Workflow Pack demo data ──────────────────────────────────────────────────
// Drives the /demo interactive experience. No CRE assumptions outside crePack.

export const DEMO_PACKS = {
  cre: {
    id: 'cre',
    name: 'Commercial Real Estate',
    badge: 'CRE',
    tagline: 'Loan origination, compliance & asset management',
    accentColor: '#9f1239',
    stages: ['Letter of Intent', 'Due Diligence', 'Financing', 'Closing'],
    currentStage: 1,
    sampleDealName: '850 Park Avenue — Bridge Acquisition',
    roles: [
      { name: 'Borrower',      description: 'Entity acquiring or refinancing the asset',  initials: 'BR', color: '#7c3aed', invited: true },
      { name: 'Lender',        description: 'Capital provider reviewing loan request',     initials: 'LE', color: '#0891b2', invited: true },
      { name: 'Broker',        description: 'Transaction intermediary',                   initials: 'BK', color: '#059669', invited: true },
      { name: 'Appraiser',     description: 'Independent valuation specialist',           initials: 'AP', color: '#d97706', invited: false },
      { name: 'Legal Counsel', description: 'Closing documentation & title',              initials: 'LC', color: '#dc2626', invited: false },
    ],
    checklist: [
      { id: 't12',       label: 'T12 Financial Statement',   required: true,  status: 'complete',    role: 'Borrower' },
      { id: 'rentroll',  label: 'Rent Roll',                 required: true,  status: 'complete',    role: 'Borrower' },
      { id: 'appraisal', label: 'Appraisal Report',          required: true,  status: 'in_progress', role: 'Appraiser' },
      { id: 'env',       label: 'Phase I Environmental',     required: true,  status: 'pending',     role: 'Borrower' },
      { id: 'insurance', label: 'Property Insurance Binder', required: true,  status: 'pending',     role: 'Borrower' },
      { id: 'survey',    label: 'ALTA Survey',               required: false, status: 'pending',     role: 'Borrower' },
      { id: 'loan',      label: 'Loan Agreement Draft',      required: true,  status: 'pending',     role: 'Legal Counsel' },
    ],
    insights: {
      score: 74, grade: 'B+',
      summary: 'Strong occupancy at 94.2% with stable NOI. DSCR of 1.32x exceeds minimum threshold. Phase I Environmental pending — proceed with financing once filed.',
      metrics: [
        { label: 'Occupancy', value: '94.2%', trend: 'up',   good: true  },
        { label: 'DSCR',      value: '1.32x', trend: 'up',   good: true  },
        { label: 'LTV',       value: '62.8%', trend: 'down', good: true  },
        { label: 'NOI Δ',     value: '-3.1%', trend: 'down', good: false },
      ],
      risks: [
        { level: 'medium', title: 'DSCR approaching 1.25x covenant', detail: 'Current at 1.32x — 5.5% margin from threshold' },
        { level: 'low',    title: 'Tenant concentration',            detail: '2 anchor tenants represent 38% of NRA' },
      ],
    },
    audit: [
      { actor: 'System',   action: 'Workspace created with CRE Workflow Pack',          time: '2h ago' },
      { actor: 'Borrower', action: 'Uploaded T12 Financial Statement',                  time: '1h 45m ago' },
      { actor: 'AI',       action: 'Extracted 47 financial data points from T12',       time: '1h 44m ago' },
      { actor: 'Borrower', action: 'Uploaded Rent Roll (32 units)',                     time: '1h 30m ago' },
      { actor: 'Lender',   action: 'Reviewed financials — flagged DSCR margin',        time: '1h ago' },
      { actor: 'Broker',   action: 'Confirmed appraisal order placed',                 time: '45m ago' },
    ],
  },

  acquisition: {
    id: 'acquisition',
    name: 'Business Acquisition',
    badge: 'M&A',
    tagline: 'M&A transactions from NDA through close',
    accentColor: '#1d4ed8',
    stages: ['NDA & Exclusivity', 'Valuation & IOI', 'Due Diligence', 'LOI & Negotiation', 'Closing'],
    currentStage: 2,
    sampleDealName: 'Meridian SaaS — Strategic Acquisition',
    roles: [
      { name: 'Buyer',          description: 'Acquiring entity conducting purchase',       initials: 'BY', color: '#1d4ed8', invited: true },
      { name: 'Seller',         description: 'Business owner / management team',          initials: 'SL', color: '#7c3aed', invited: true },
      { name: 'M&A Advisor',    description: 'Transaction intermediary & process lead',   initials: 'MA', color: '#059669', invited: true },
      { name: 'QoE Accountant', description: 'Financial due diligence & QoE report',     initials: 'QE', color: '#d97706', invited: true },
      { name: 'Legal Counsel',  description: 'Purchase agreement & deal structure',       initials: 'LC', color: '#dc2626', invited: false },
    ],
    checklist: [
      { id: 'cim',       label: 'Confidential Information Memorandum', required: true,  status: 'complete',    role: 'M&A Advisor' },
      { id: 'financials',label: '3-Year Audited Financials',           required: true,  status: 'complete',    role: 'Seller' },
      { id: 'tax',       label: 'Tax Returns (3 Years)',               required: true,  status: 'complete',    role: 'Seller' },
      { id: 'qoe',       label: 'Quality of Earnings Report',          required: true,  status: 'in_progress', role: 'QoE Accountant' },
      { id: 'loi',       label: 'Letter of Intent (Signed)',           required: true,  status: 'in_progress', role: 'Buyer' },
      { id: 'contracts', label: 'Key Customer Contracts',              required: true,  status: 'pending',     role: 'Seller' },
      { id: 'ip',        label: 'IP & Patent Schedule',               required: false, status: 'pending',     role: 'Seller' },
      { id: 'spa',       label: 'Stock Purchase Agreement',           required: true,  status: 'pending',     role: 'Legal Counsel' },
    ],
    insights: {
      score: 81, grade: 'A-',
      summary: 'Revenue growth of 28% YoY with healthy EBITDA margins of 22%. QoE in progress — preliminary findings show normalized EBITDA of $4.2M. Customer concentration is the primary watch item.',
      metrics: [
        { label: 'Rev Growth',    value: '+28% YoY', trend: 'up',   good: true  },
        { label: 'EBITDA Margin', value: '22%',      trend: 'up',   good: true  },
        { label: 'NRR',           value: '118%',     trend: 'up',   good: true  },
        { label: 'Churn',         value: '4.2%',     trend: 'up',   good: false },
      ],
      risks: [
        { level: 'medium', title: 'Customer concentration', detail: 'Top 3 customers represent 52% of revenue' },
        { level: 'low',    title: 'Key person dependency',  detail: 'Founder drives 3 of top 5 customer relationships' },
      ],
    },
    audit: [
      { actor: 'System',       action: 'Workspace created with Business Acquisition Workflow Pack', time: '3h ago' },
      { actor: 'M&A Advisor',  action: 'Uploaded Confidential Information Memorandum',             time: '2h 50m ago' },
      { actor: 'AI',           action: 'Identified 12 financial risk signals in CIM',              time: '2h 49m ago' },
      { actor: 'Seller',       action: 'Uploaded 3-year audited financials',                       time: '2h ago' },
      { actor: 'QoE Accountant', action: 'Started Quality of Earnings analysis',                  time: '1h 20m ago' },
      { actor: 'Buyer',        action: 'Signed NDA — exclusivity period begins',                  time: '30m ago' },
    ],
  },

  fundraising: {
    id: 'fundraising',
    name: 'Capital Raise',
    badge: 'VC',
    tagline: 'Equity rounds, venture capital & structured capital',
    accentColor: '#6d28d9',
    stages: ['Term Sheet', 'Investor Diligence', 'Documentation', 'Final Close'],
    currentStage: 1,
    sampleDealName: 'Nexus AI — Series B Capital Raise',
    roles: [
      { name: 'Company / Issuer',  description: 'Entity raising capital',                      initials: 'CO', color: '#6d28d9', invited: true },
      { name: 'Lead Investor',     description: 'Anchor investor setting terms',               initials: 'LI', color: '#1d4ed8', invited: true },
      { name: 'Co-Investor',       description: 'Participating alongside lead',                initials: 'CI', color: '#059669', invited: true },
      { name: 'Legal Counsel',     description: 'Subscription docs & regulatory compliance',  initials: 'LC', color: '#dc2626', invited: false },
      { name: 'Financial Advisor', description: 'Placement agent or investment banker',       initials: 'FA', color: '#d97706', invited: false },
    ],
    checklist: [
      { id: 'deck',         label: 'Investor Pitch Deck',                  required: true,  status: 'complete',    role: 'Company / Issuer' },
      { id: 'model',        label: 'Financial Model & 5-Year Projections', required: true,  status: 'complete',    role: 'Company / Issuer' },
      { id: 'captable',     label: 'Cap Table (Pre & Post-Money)',         required: true,  status: 'complete',    role: 'Company / Issuer' },
      { id: 'termsheet',    label: 'Signed Term Sheet',                    required: true,  status: 'in_progress', role: 'Lead Investor' },
      { id: 'ddq',          label: 'Due Diligence Questionnaire',          required: true,  status: 'in_progress', role: 'Company / Issuer' },
      { id: 'subscription', label: 'Subscription Agreement',              required: true,  status: 'pending',     role: 'Legal Counsel' },
      { id: 'sideletter',   label: 'Side Letter (Lead Investor)',          required: false, status: 'pending',     role: 'Legal Counsel' },
      { id: 'legal',        label: 'Legal Opinion',                        required: true,  status: 'pending',     role: 'Legal Counsel' },
    ],
    insights: {
      score: 88, grade: 'A',
      summary: 'Compelling unit economics with 3.2x LTV:CAC ratio and 94% gross margins. ARR of $8.4M growing at 140% NRR. Term sheet review in progress at $42M post-money.',
      metrics: [
        { label: 'ARR',         value: '$8.4M', trend: 'up',   good: true },
        { label: 'Gross Margin', value: '94%',   trend: 'up',   good: true },
        { label: 'NRR',         value: '140%',  trend: 'up',   good: true },
        { label: 'CAC Payback', value: '8 mo',  trend: 'down', good: true },
      ],
      risks: [
        { level: 'low', title: 'Regulatory filing',     detail: 'Reg D filing required within 15 days of first close' },
        { level: 'low', title: 'Valuation sensitivity', detail: 'Post-money $42M — 12x ARR vs. 11x peer median' },
      ],
    },
    audit: [
      { actor: 'System',          action: 'Workspace created with Capital Raise Workflow Pack',    time: '1h ago' },
      { actor: 'Company / Issuer',action: 'Uploaded Investor Pitch Deck (42 slides)',              time: '58m ago' },
      { actor: 'AI',              action: 'Benchmarked financials against 240 comparable rounds', time: '57m ago' },
      { actor: 'Company / Issuer',action: 'Uploaded Financial Model & Cap Table',                 time: '45m ago' },
      { actor: 'Lead Investor',   action: 'Reviewed materials — initiated term sheet',            time: '20m ago' },
      { actor: 'AI',              action: 'Deal score updated to 88 / A',                         time: '19m ago' },
    ],
  },
};
