-- Durable, auditable AI room-generation sessions.
create table if not exists transaction_generation_sessions (
  id uuid primary key,
  description text not null,
  transaction_type text,
  status text not null default 'draft' check (status in ('draft', 'approved', 'created', 'superseded')),
  proposal jsonb not null,
  edited_proposal jsonb,
  approved_snapshot jsonb,
  generation_proof text,
  model text,
  generation_version text not null default '1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  created_room_id text
);

create index if not exists transaction_generation_sessions_status_idx
  on transaction_generation_sessions(status, updated_at desc);

create table if not exists transaction_generation_sources (
  id bigint generated by default as identity primary key,
  session_id uuid not null references transaction_generation_sessions(id) on delete cascade,
  requirement_key text,
  source_type text not null check (source_type in ('authoritative', 'uploaded', 'template', 'ai_recommendation')),
  source_title text,
  source_url text,
  source_excerpt text,
  created_at timestamptz not null default now()
);

create index if not exists transaction_generation_sources_session_idx
  on transaction_generation_sources(session_id);

create or replace function set_transaction_generation_sessions_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists transaction_generation_sessions_updated_at on transaction_generation_sessions;
create trigger transaction_generation_sessions_updated_at
before update on transaction_generation_sessions
for each row execute function set_transaction_generation_sessions_updated_at();