// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SettlementStates.tsx": () => import("../components/mockups/SettlementStates.tsx"),
  "./components/mockups/Settlement_Digital.tsx": () => import("../components/mockups/Settlement_Digital.tsx"),
  "./components/mockups/Settlement_Sealed.tsx": () => import("../components/mockups/Settlement_Sealed.tsx"),
  "./components/mockups/Settlement_Tokenized.tsx": () => import("../components/mockups/Settlement_Tokenized.tsx"),
  "./components/mockups/Settlement_Traditional.tsx": () => import("../components/mockups/Settlement_Traditional.tsx"),
  "./components/mockups/login-themes/BrutalistEdge.tsx": () => import("../components/mockups/login-themes/BrutalistEdge.tsx"),
  "./components/mockups/login-themes/CrimsonCard.tsx": () => import("../components/mockups/login-themes/CrimsonCard.tsx"),
  "./components/mockups/login-themes/Executive.tsx": () => import("../components/mockups/login-themes/Executive.tsx")
};
