// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-themes/BrutalistEdge.tsx": () => import("../components/mockups/login-themes/BrutalistEdge.tsx"),
  "./components/mockups/login-themes/CrimsonCard.tsx": () => import("../components/mockups/login-themes/CrimsonCard.tsx"),
  "./components/mockups/login-themes/Executive.tsx": () => import("../components/mockups/login-themes/Executive.tsx")
};
