export const nav = [
  "Assets",
  "Inspections",
  "Dashboard",
  "Loans",
  "Draws",
  "Projects",
  "Organizations",
  "Invites",
  "Document Review",
  "SSO",
  "Reports",
  "Menu",
  "Orders",
  "Payments",
  "Payoff Instructions",
  "Escrow",
  "Delinquency Alerts",
  "Trades",
  "Exchange",
  "Analytics",
  "Restaurant Ops",
  "Applications",
  "Risk",
  "Servicing",
  "Webhooks",
  "Subscriptions",
];

export default nav;
