export type Severity = "blocker" | "high" | "medium";

export type ActionRegistryItem = {
  id: string;
   label: string;
  route: string;
 uiPath: string;
  requiredApis: string[];
  requiredRoutes?: string[];
  featureFlag?: string;
  severity: Severity;
};

export const actionRegistry: ActionRegistryItem[] = [
  {
    id: "dashboard.summary",
    label: "Dashboard > Summary",
    route: "/dashboard",
   uiPath: "ui/src/components/SaasDashboardHome.tsx",
    requiredApis: ["GET /api/dashboard/summary"],
      requiredRoutes: ["/dashboard"],
    severity: "blocker",
  },
  {
    id: "portfolio.loans.list",
    label: "Portfolio > Loans list",
    route: "/portfolio/loans",
   uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/portfolio/loans", "POST /api/portfolio/loans"],
    requiredRoutes: ["/portfolio", "/portfolio/loans"],
    severity: "blocker",
  },
  {
    id: "portfolio.assets.list",
    label: "Portfolio > Assets list",
    route: "/portfolio/assets",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/portfolio/assets", "POST /api/portfolio/assets"],
    requiredRoutes: ["/portfolio/assets"],
    severity: "blocker",
  },
  {
    id: "servicing.payments.list",
    label: "Servicing > Payments",
    route: "/servicing/payments",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/payments", "POST /api/servicing/payments"],
    requiredRoutes: ["/servicing/payments"],
    severity: "blocker",
  },
  {
    id: "servicing.inspections.list",
    label: "Servicing > Inspections",
    route: "/servicing/inspections",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/inspections", "POST /api/servicing/inspections"],
    requiredRoutes: ["/servicing/inspections"],
    severity: "blocker",
  },
  {
    id: "servicing.draws.list",
    label: "Servicing > Draws",
    route: "/servicing/draws",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/draws", "POST /api/servicing/draws"],
    requiredRoutes: ["/servicing/draws"],
    severity: "blocker",
  },
  {
    id: "servicing.escrow.list",
    label: "Servicing > Escrow",
    route: "/servicing/escrow",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/escrows", "POST /api/servicing/escrows"],
    requiredRoutes: ["/servicing/escrow"],
    severity: "high",
  },
  {
    id: "servicing.borrowerFinancials.list",
    label: "Servicing > Borrower Financials",
    route: "/servicing/borrower-financials",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/borrower-financials", "POST /api/servicing/borrower-financials"],
    requiredRoutes: ["/servicing/borrower-financials"],
    severity: "high",
  },
  {
    id: "servicing.management.list",
    label: "Servicing > Management",
    route: "/servicing/management",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/servicing/management", "POST /api/servicing/management"],
    requiredRoutes: ["/servicing/management"],
    severity: "high",
  },
  {
    id: "servicing.aiValidation.list",
    label: "Servicing > AI Validation",
    route: "/analytics",
    uiPath: "ui/src/features/ai-insights/page/AiInsightsPage.tsx",
    requiredApis: ["GET /api/ai/reviews"],
    requiredRoutes: ["/analytics"],
    severity: "high",
  },
  {
    id: "markets.pools.list",
    label: "Capital Markets > Pools",
    route: "/markets/pools",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/markets/pools", "POST /api/markets/pools", "POST /api/markets/pools/:id/loans"],
    requiredRoutes: ["/markets/pools"],
    severity: "blocker",
  },
  {
    id: "markets.tokens.list",
    label: "Capital Markets > Tokens",
    route: "/markets/tokens",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/markets/tokens", "POST /api/markets/tokens"],
    requiredRoutes: ["/markets/tokens"],
    severity: "high",
  },
  {
    id: "markets.trades.list",
    label: "Capital Markets > Trades",
    route: "/markets/trades",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/markets/trades", "POST /api/markets/trades"],
    requiredRoutes: ["/markets/trades"],
    severity: "high",
  },
  {
    id: "markets.exchange.list",
    label: "Capital Markets > Exchange Listings",
    route: "/markets/exchange",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/markets/exchange-listings", "POST /api/markets/exchange-listings"],
    requiredRoutes: ["/markets/exchange"],
    severity: "high",
  },
  {
    id: "governance.compliance.list",
    label: "Governance > Compliance",
    route: "/governance/compliance",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/governance/compliance-items", "POST /api/governance/compliance-items"],
    requiredRoutes: ["/governance/compliance"],
    severity: "high",
  },
  {
    id: "governance.legal.list",
    label: "Governance > Legal",
    route: "/governance/legal",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/governance/legal-items", "POST /api/governance/legal-items"],
    requiredRoutes: ["/governance/legal"],
    severity: "high",
  },
  {
    id: "governance.regulatoryScans.list",
    label: "Governance > Regulatory Scans",
    route: "/governance/regulatory-scans",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/governance/regulatory-scans", "POST /api/governance/regulatory-scans"],
    requiredRoutes: ["/governance/regulatory-scans"],
    severity: "high",
  },
  {
    id: "governance.risk.list",
    label: "Governance > Risk",
    route: "/governance/risk",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/governance/risk-items", "POST /api/governance/risk-items"],
    requiredRoutes: ["/governance/risk"],
    severity: "high",
  },
  {
    id: "governance.documentReviews.list",
    label: "Governance > Document Reviews",
    route: "/governance/document-review",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/governance/document-reviews", "POST /api/governance/document-reviews"],
    requiredRoutes: ["/governance/document-review"],
    severity: "high",
  },
  {
    id: "reports.list",
    label: "Reports > List",
    route: "/reports",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/reports/reports", "POST /api/reports/reports"],
    requiredRoutes: ["/reports"],
    severity: "high",
  },
  {
    id: "organizations.list",
    label: "Organizations > List",
    route: "/organizations",
    uiPath: "ui/src/pages/dashboard/canonical/pages.tsx",
    requiredApis: ["GET /api/orgs", "POST /api/orgs"],
    requiredRoutes: ["/organizations"],
    severity: "blocker",
  },
  {
    id: "organizations.members",
    label: "Organizations > Members",
    route: "/organizations",
    uiPath: "ui/src/features/organizations/members/api.ts",
    requiredApis: ["GET /api/orgs/:id/members", "POST /api/orgs/:id/members"],
    severity: "high",
  },
  {
    id: "settings.sso",
    label: "Settings > SSO",
    route: "/settings/sso",
    uiPath: "ui/src/pages/settings/SsoSettingsPage.tsx",
    requiredApis: ["GET /api/sso/config"],
    requiredRoutes: ["/settings/sso"],
    featureFlag: "sso",
    severity: "medium",
  },
    ];

export const actionRegistryByRoute = new Map(actionRegistry.map((item) => [item.route, item]));
