export const routeCatalog = [
  "/dashboard",
  "/portfolio",
  "/portfolio/loans",
  "/portfolio/assets",
  "/servicing",
  "/servicing/payments",
  "/servicing/inspections",
  "/servicing/draws",
  "/servicing/escrow",
  "/servicing/borrower-financials",
  "/servicing/management",
  "/markets",
  "/markets/pools",
  "/markets/tokens",
  "/markets/trades",
  "/markets/exchange",
  "/governance",
  "/governance/compliance",
  "/governance/legal",
  "/governance/regulatory-scans",
  "/governance/document-review",
  "/governance/risk",
  "/analytics",
  "/reports",
  "/organizations",
  "/settings/sso",
  "/settings/api-diagnostics",
  "/dev/wiring-check",
] as const;

export type AppRoute = (typeof routeCatalog)[number];
